[package]
name = "quadio-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
cuet.workspace = true
hound.workspace = true
quadio-core = { path = "../core" }
cpal.workspace = true
libc = { version = "^0.2.155" }
